name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/whiteduck/DevOps'
        azure-pipeline-name: 'mbrtest'
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}’

